version: '3.8'

services:
  knext:
    build: .
    ports:
      - "3050:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_PATH=./data/db.sqlite
    volumes:
      - knext_data:/app/data

volumes:
  knext_data: