services:
  knext:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_PATH: /app/data/db.sqlite
    volumes:
      - knext_data:/app/data

volumes:
  knext_data:
